apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::791661263800:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-I7TZXRIM2M4X
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::791661263800:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-29T23:49:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3651"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 26f448ee-b07a-49ee-90c5-3001c255033a